import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";

import { writeAtomic } from "./atomic.ts";
import { parseNote } from "./frontmatter.ts";
import { vaultPaths } from "./vault.ts";

/** Default `_hot.md` size budget, in words. Overridable via TRAIL_HOT_BUDGET. */
export const DEFAULT_HOT_BUDGET = 400;

const MAX_DECISIONS = 5;

interface TaskEntry {
  slug: string;
  title: string;
  ticket?: string;
  summary?: string;
}

interface DecisionEntry {
  slug: string;
  title: string;
  date: string;
}

/** Resolve the word budget for `_hot.md` (TRAIL_HOT_BUDGET, falling back to the default). */
export function hotBudget(): number {
  const raw = process.env["TRAIL_HOT_BUDGET"];
  if (raw) {
    const parsed = Number.parseInt(raw, 10);
    if (Number.isFinite(parsed) && parsed > 0) return parsed;
  }
  return DEFAULT_HOT_BUDGET;
}

/** Count words the same way the budget warning does: whitespace-delimited tokens. */
export function countWords(text: string): number {
  const tokens = text.trim().split(/\s+/);
  return tokens.length === 1 && tokens[0] === "" ? 0 : tokens.length;
}

export interface HotStatus {
  words: number;
  budget: number;
  overBudget: boolean;
  activeTasks: number;
}

/** Read `_hot.md` from disk and report its size against the budget. */
export function checkHot(root: string): HotStatus {
  const paths = vaultPaths(root);
  const budget = hotBudget();
  const content = existsSync(paths.hot) ? readFileSync(paths.hot, "utf8") : "";
  const words = countWords(content);
  const activeTasks = listMarkdown(paths.wip).length;
  return { words, budget, overBudget: words > budget, activeTasks };
}

/**
 * Regenerate `_hot.md` from the live `WIP/` tasks and the most recent decisions.
 * Every active task gets a one-line link; size is reported (not trimmed) so the
 * over-budget warning reflects the real snapshot — too many tasks in flight.
 */
export function regenerateHot(root: string): HotStatus {
  const paths = vaultPaths(root);
  const budget = hotBudget();

  const tasks = readTasks(paths.wip);
  const decisions = readDecisions(paths.decisions).slice(0, MAX_DECISIONS);

  const content = renderHot(tasks, decisions);
  writeAtomic(paths.hot, content);

  const words = countWords(content);
  return { words, budget, overBudget: words > budget, activeTasks: tasks.length };
}

function renderHot(tasks: TaskEntry[], decisions: DecisionEntry[]): string {
  const lines: string[] = ["# 🔥 hot context", "", "_Regenerated by trail. Do not hand-edit._", ""];

  lines.push("## Active tasks");
  lines.push("");
  if (tasks.length === 0) {
    lines.push('No active tasks. Run `trail task "<title>"` to start one.');
  } else {
    for (const task of tasks) {
      const ticket = task.ticket ? ` (${task.ticket})` : "";
      const summary = task.summary ? ` — ${task.summary}` : "";
      lines.push(`- [[WIP/${task.slug}|${task.title}]]${ticket}${summary}`);
    }
  }
  lines.push("");

  if (decisions.length > 0) {
    lines.push("## Recent decisions");
    lines.push("");
    for (const decision of decisions) {
      lines.push(`- [[Decisions/${decision.slug}|${decision.title}]] · ${decision.date}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function readTasks(wipDir: string): TaskEntry[] {
  const entries: { entry: TaskEntry; created: string }[] = [];
  for (const file of listMarkdown(wipDir)) {
    const { frontmatter, body } = parseNote(readFileSync(join(wipDir, file), "utf8"));
    const slug = frontmatter.slug ?? basename(file, ".md");
    const summary = lastTimelineSummary(body);
    const entry: TaskEntry = {
      slug,
      title: headingOf(body) ?? slug,
      ...(frontmatter.ticket ? { ticket: frontmatter.ticket } : {}),
      ...(summary ? { summary } : {}),
    };
    entries.push({ entry, created: frontmatter.created ?? "" });
  }
  // Most recently created first.
  entries.sort((a, b) => b.created.localeCompare(a.created));
  return entries.map((e) => e.entry);
}

function readDecisions(decisionsDir: string): DecisionEntry[] {
  const entries: DecisionEntry[] = [];
  for (const file of listMarkdown(decisionsDir)) {
    const { frontmatter, body } = parseNote(readFileSync(join(decisionsDir, file), "utf8"));
    const slug = basename(file, ".md");
    entries.push({
      slug,
      title: headingOf(body) ?? frontmatter.slug ?? slug,
      date: frontmatter.created ?? "",
    });
  }
  // Newest first by filename, which is `YYYY-MM-DD-<slug>` and therefore sortable.
  entries.sort((a, b) => b.slug.localeCompare(a.slug));
  return entries;
}

function listMarkdown(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => name.endsWith(".md") && name !== ".gitkeep")
    .sort();
}

function headingOf(body: string): string | undefined {
  for (const line of body.split("\n")) {
    const match = line.match(/^#\s+(.*\S)\s*$/);
    if (match) return match[1];
  }
  return undefined;
}

/** Last timeline entry's text (the part after the `HH:MM · author · agent` stamp). */
function lastTimelineSummary(body: string): string | undefined {
  const lines = body.split("\n");
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i];
    if (line === undefined) continue;
    const match = line.match(/^-\s+\d{2}:\d{2}\s+·\s+[^·]+·\s+\S+\s+(.+\S)\s*$/);
    if (match) return match[1];
  }
  return undefined;
}
