import { serializeNote } from "./frontmatter.ts";
import type { Frontmatter } from "./frontmatter.ts";

export interface TaskInput {
  title: string;
  slug: string;
  author: string;
  agent: string;
  created: string;
  ticket?: string;
  tags?: string[];
}

export interface DecisionInput {
  title: string;
  slug: string;
  author: string;
  agent: string;
  created: string;
  ticket?: string;
}

export interface ResearchInput {
  title: string;
  slug: string;
  author: string;
  agent: string;
  created: string;
}

export function taskTemplate(input: TaskInput): string {
  const fm: Frontmatter = {
    type: "task",
    status: "wip",
    slug: input.slug,
    author: input.author,
    agent: input.agent,
    created: input.created,
    ...(input.ticket ? { ticket: input.ticket } : {}),
    ...(input.tags && input.tags.length > 0 ? { tags: input.tags } : {}),
  };
  const body = `\n# ${input.title}\n\n## Objetivo\n\n## Plan\n\n## Timeline\n`;
  return serializeNote(fm, body);
}

export function decisionTemplate(input: DecisionInput): string {
  const fm: Frontmatter = {
    type: "decision",
    slug: input.slug,
    author: input.author,
    agent: input.agent,
    created: input.created,
    ...(input.ticket ? { ticket: input.ticket } : {}),
  };
  const body = `\n# ${input.title}\n\n## Contexto\n\n## Decisión\n\n## Alternativas\n\n## Consecuencias\n`;
  return serializeNote(fm, body);
}

export function researchTemplate(input: ResearchInput): string {
  const fm: Frontmatter = {
    type: "research",
    slug: input.slug,
    author: input.author,
    agent: input.agent,
    created: input.created,
  };
  const body = `\n# ${input.title}\n\n## Pregunta\n\n## TL;DR\n\n## Hallazgos\n\n## Aplicabilidad\n`;
  return serializeNote(fm, body);
}

export function emptyHot(): string {
  return `# 🔥 hot context\n\n_Regenerated by trail. Do not hand-edit._\n\nNo active tasks yet. Run \`trail task "<title>"\` to start one.\n`;
}

export const OBSIDIAN_FILES: Record<string, string> = {
  "app.json": json({
    promptDelete: false,
    alwaysUpdateLinks: true,
    newFileLocation: "current",
    attachmentFolderPath: "./",
    showLineNumber: true,
    readableLineLength: true,
  }),
  "appearance.json": json({
    accentColor: "#f97316",
    theme: "obsidian",
    cssTheme: "",
    interfaceFontFamily: "",
    textFontFamily: "",
    monospaceFontFamily: "",
  }),
  "core-plugins.json": json({
    "file-explorer": true,
    search: true,
    "global-search": true,
    graph: true,
    backlink: true,
    "outgoing-link": true,
    "tag-pane": true,
    properties: true,
    "page-preview": true,
    "daily-notes": false,
    templates: false,
    "note-composer": true,
    "command-palette": true,
    "markdown-importer": false,
    "word-count": true,
    "file-recovery": true,
  }),
  "graph.json": json({
    "collapse-filter": true,
    search: "",
    showTags: false,
    showAttachments: false,
    hideUnresolved: false,
    showOrphans: true,
    "collapse-color-groups": false,
    colorGroups: [
      { query: "path:WIP", color: { a: 1, rgb: 16351523 } },
      { query: "path:Decisions", color: { a: 1, rgb: 4233215 } },
      { query: "path:Research", color: { a: 1, rgb: 4445941 } },
      { query: "path:DONE", color: { a: 1, rgb: 7041892 } },
      { query: "path:PAUSED", color: { a: 1, rgb: 10066329 } },
    ],
    "collapse-display": false,
    showArrow: true,
    textFadeMultiplier: 0,
    nodeSizeMultiplier: 1.1,
    lineSizeMultiplier: 1,
    "collapse-forces": false,
    centerStrength: 0.52,
    repelStrength: 11,
    linkStrength: 1,
    linkDistance: 230,
    scale: 1,
  }),
};

export function obsidianGitignore(): string {
  return ".locks/\n.obsidian/\n";
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
}
