import { serializeNote } from "./frontmatter.ts";
import type { Frontmatter } from "./frontmatter.ts";

export interface TaskInput {
  title: string;
  slug: string;
  author: string;
  agent: string;
  created: string;
  ticket?: string;
  tags?: string[];
}

export interface DecisionInput {
  title: string;
  slug: string;
  author: string;
  agent: string;
  created: string;
  ticket?: string;
}

export interface ResearchInput {
  title: string;
  slug: string;
  author: string;
  agent: string;
  created: string;
}

export function taskTemplate(input: TaskInput): string {
  const fm: Frontmatter = {
    type: "task",
    status: "wip",
    slug: input.slug,
    author: input.author,
    agent: input.agent,
    created: input.created,
    ticket: input.ticket,
    tags: input.tags,
  };
  const body = `\n# ${input.title}\n\n## Objective\n\n## Plan\n\n## Timeline\n`;
  return serializeNote(fm, body);
}

export function decisionTemplate(input: DecisionInput): string {
  const fm: Frontmatter = {
    type: "decision",
    slug: input.slug,
    author: input.author,
    agent: input.agent,
    created: input.created,
    ticket: input.ticket,
  };
  const body = `\n# ${input.title}\n\n## Context\n\n## Decision\n\n## Alternatives\n\n## Consequences\n`;
  return serializeNote(fm, body);
}

export function researchTemplate(input: ResearchInput): string {
  const fm: Frontmatter = {
    type: "research",
    slug: input.slug,
    author: input.author,
    agent: input.agent,
    created: input.created,
  };
  const body = `\n# ${input.title}\n\n## Question\n\n## TL;DR\n\n## Findings\n\n## Applicability\n`;
  return serializeNote(fm, body);
}

export function emptyHot(): string {
  return `# 🔥 hot context\n\n_Regenerated by trail. Do not hand-edit._\n\nNo active tasks yet. Run \`trail task "<title>"\` to start one.\n`;
}

/** `.trail/.gitignore` — Obsidian writes its own `.obsidian/` on first open; keep it local. */
export function obsidianGitignore(): string {
  return ".obsidian/\n";
}
